# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_payed', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(to='webshop_app.Item')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_country',
            field=models.CharField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
