# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0003_auto_20180205_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_country',
            field=models.DecimalField(choices=[(0.12, 'United States'), (0.14, 'Europe'), (0.3, 'Asia')], decimal_places=2, max_digits=2),
        ),
    ]
