# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0004_auto_20180205_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_country',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
