# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0005_auto_20180205_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_country',
            new_name='addrss_country',
        ),
    ]
